# Generated by Django 5.0.13 on 2025-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_he', models.CharField(max_length=200, verbose_name='Title (Hebrew)')),
                ('short_description_en', models.TextField(verbose_name='Short Description (English)')),
                ('short_description_he', models.TextField(verbose_name='Short Description (Hebrew)')),
                ('external_link', models.URLField(verbose_name='Contact or Purchase Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
