# Generated by Django 5.0.13 on 2025-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_he',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_he',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='Unnamed Product', max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_he',
            field=models.CharField(default='Unnamed Product', max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='store/', verbose_name='Product Image'),
        ),
    ]
