# Generated by Django 5.0.13 on 2025-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=100, verbose_name='Label (English)')),
                ('label_he', models.CharField(max_length=100, verbose_name='Label (Hebrew)')),
                ('url', models.URLField(verbose_name='URL')),
                ('position', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_he', models.CharField(max_length=200, verbose_name='Title (Hebrew)')),
                ('slug', models.SlugField(unique=True)),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_he', models.TextField(verbose_name='Content (Hebrew)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Menu Order')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField(verbose_name='Main Office Location')),
                ('additional_locations', models.TextField(blank=True, null=True, verbose_name='Additional Locations')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Footer Text')),
                ('terms_url', models.URLField(blank=True, null=True, verbose_name='Terms & Conditions URL')),
                ('privacy_url', models.URLField(blank=True, null=True, verbose_name='Privacy Policy URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
