# Generated by Django 5.0.13 on 2025-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Company Logo'),
        ),
    ]
