# Generated by Django 5.0.13 on 2025-03-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesetting_additional_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='privacy_url',
            field=models.CharField(blank=True, default='/privacy/', max_length=255, null=True, verbose_name='Privacy Policy URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='terms_url',
            field=models.CharField(blank=True, default='/terms/', max_length=255, null=True, verbose_name='Terms & Conditions URL'),
        ),
    ]
