# Generated by Django 5.0.13 on 2025-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesetting_privacy_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
