# Generated by Django 5.0.13 on 2025-03-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_navlink_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navlink',
            name='url',
        ),
        migrations.AddField(
            model_name='navlink',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL (For Social Media or External Pages)'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='internal_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page', verbose_name='Internal Page'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Is External Link?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
