# Generated by Django 5.0.13 on 2025-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_navlink_url_navlink_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='navlink',
            name='internal_page',
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='NavLink',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
