# Generated by Django 5.0.13 on 2025-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_remove_navlink_internal_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_he',
            field=models.CharField(max_length=200, null=True, verbose_name='Site Name'),
        ),
    ]
