# Generated by Django 5.0.13 on 2025-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_site_name_en_sitesettings_site_name_he'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_name_en', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('company_name_he', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('address_en', models.TextField(null=True, verbose_name='Address')),
                ('address_he', models.TextField(null=True, verbose_name='Address')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_he', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('subtitle_he', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('background_image', models.ImageField(upload_to='hero_images/', verbose_name='Background Image')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_he', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('url', models.CharField(max_length=200, verbose_name='URL Path')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_he', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('feedback_en', models.TextField(null=True, verbose_name='Feedback')),
                ('feedback_he', models.TextField(null=True, verbose_name='Feedback')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='User Image')),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
