# Generated by Django 5.0.13 on 2025-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_footersection_herosection_navbaritem_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Company Logo'),
        ),
    ]
