# Generated by Django 5.0.13 on 2025-03-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavbarItem',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Location'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Location'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_location_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Location'),
        ),
    ]
