# Generated by Django 5.0.13 on 2025-03-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Category (English)')),
                ('name_he', models.CharField(max_length=100, verbose_name='Category (Hebrew)')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_he', models.CharField(max_length=200, verbose_name='Title (Hebrew)')),
                ('slug', models.SlugField(unique=True)),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_he', models.TextField(verbose_name='Content (Hebrew)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Featured Image')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Author')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description (SEO)')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
