# Generated by Django 5.0.13 on 2025-03-19 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='No content available.', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Untitled Article', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(default='No content available.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_he',
            field=models.TextField(default='No content available.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='Untitled Article', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_he',
            field=models.CharField(default='Untitled Article', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
